# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Teabough's blog
tagline:          Yet another personnal blog about computer science ... 
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           TeaBough
  url:            https://twitter.com/teaBough
  email:          thibault.vigouroux@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/TeaBough
